Description of output_tests_from_mfile
Home > mlunit > test_loader_R2015b > output_tests_from_mfile.m
output_tests_from_mfile
PURPOSE
Build a test_suite with all test* methods from a .m-file.
SYNOPSIS
This is a script file.
DESCRIPTION
Build a test_suite with all test* methods from a .m-file.
Use this in a function test suite's main function in order to let mlUnit access
its subfunctions.
This needs to be a script rather than a function, in order to obtain the
subfunction handles, which, from R2015b on, only works if executed from within
the function test suite file.
Because it is a script, its implementation is tight, i.e. tries not to drop
temporary variables unnecessarily. The only variables created are "call_stack"
and "test".
  Example
  =======
  output_tests_from_mfile is called from within the .m-file that contains
  the test* methods. The return parameter MUST be named "test":
         function test = test_example
             output_tests_from_mfile;
         end
         function test_method
             assert_true(0 == sin(0));
         end
  See also FUNCTION_TEST_CASE.
CROSS-REFERENCE INFORMATION
This function calls:
mlunit_progress_listener_console Console progress listener implementation.
add_listener Add a progress listener object to the list of subscribers.
mlunit_suite_runner Execute a single test suite
run_suite_collection Execute one or several test suites.
build_testsuite_object Build a test_suite object from a list of handles.
get_subfunction_names Parse a MATLAB file and return all subfunction names.
test_loader Collection of stateless loading methods.
This function is called by:
SOURCE CODE
%Build a test_suite with all test* methods from a .m-file.
%
%Use this in a function test suite's main function in order to let mlUnit access
%its subfunctions.
%
%This needs to be a script rather than a function, in order to obtain the
%subfunction handles, which, from R2015b on, only works if executed from within
%the function test suite file.
%
%Because it is a script, its implementation is tight, i.e. tries not to drop
%temporary variables unnecessarily. The only variables created are "call_stack"
%and "test".
%
%  Example
%  =======
%  output_tests_from_mfile is called from within the .m-file that contains
%  the test* methods. The return parameter MUST be named "test":
%
%         function test = test_example
%             output_tests_from_mfile;
%         end
%
%         function test_method
%             assert_true(0 == sin(0));
%         end
%
%  See also FUNCTION_TEST_CASE.
%  This Software and all associated files are released unter the
%  GNU General Public License (GPL), see LICENSE for details.
%
%  $Id$
call_stack = dbstack;
% names = get_subfunction_names(test_loader, call_stack(2).file);
% handles = cellfun(@str2func, names, 'UniformOutput', false);
% test = build_testsuite_object(test_loader, call_stack(2).name, handles);
test = build_testsuite_object(test_loader, call_stack(2).name, cellfun(@str2func, get_subfunction_names(test_loader, call_stack(2).file), 'UniformOutput', false));
% if exactly two items on call_stack, that's load_tests_from_mfile and the test
% function, meaning we were called from console directly -> execute suite
if numel(call_stack) == 2
    run_suite_collection(add_listener(mlunit_suite_runner, mlunit_progress_listener_console), call_stack(2).name);
end