Description of test_result
mlUnit > src > @test_result > test_result.m
test_result
PURPOSE
test_result contructor.
SYNOPSIS
function self = test_result
DESCRIPTION
test_result contructor.
  The constructor creates an object of the class test_result.
  Class Info
  ==========
  The class test_result collects test results of executed tests. As in
  the other testing frameworks of the xUnit family the framework
  differs between failure and error. A failure is raised by an assertion,
  that means by the method assert, while an error is raised by the Matlab
  environment, for example through a syntax error.
  Example
  =======
         result = test_result;
  See also ASSERT, ASSERT_EQUALS, ASSERT_NOT_EQUALS, TEXT_TEST_RESULT.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
gui_test_result gui_test_result contructor.
default_test_result test_case/default_test_result returns s default test_result object.
text_test_result text_test_result contructor.
SOURCE CODE
function self = test_result
%test_result contructor.
%  The constructor creates an object of the class test_result.
%
%  Class Info
%  ==========
%  The class test_result collects test results of executed tests. As in
%  the other testing frameworks of the xUnit family the framework
%  differs between failure and error. A failure is raised by an assertion,
%  that means by the method assert, while an error is raised by the Matlab
%  environment, for example through a syntax error.
%
%  Example
%  =======
%         result = test_result;
%
%  See also ASSERT, ASSERT_EQUALS, ASSERT_NOT_EQUALS, TEXT_TEST_RESULT.
self.tests_run = 0;
self.errors = {};
self.failures = {};
self.should_stop = 0;
self = class(self, 'test_result');