Description of mlunit_progress_listener_console
Home > mlunit > @mlunit_progress_listener_console > mlunit_progress_listener_console.m
mlunit_progress_listener_console
PURPOSE
Console progress listener implementation.
SYNOPSIS
function self = mlunit_progress_listener_console()
DESCRIPTION
Console progress listener implementation.
  Displays test results live on the console as they are being executed.
  See init_results, next_result
CROSS-REFERENCE INFORMATION
This function calls:
mlunit_progress_listener Abstract base class for progress listener implementations.
This function is called by:
load_tests_from_mfile test_loader/load_tests_from_mfile returns a test_suite with all
recursive_test_run RECURSIVE_TEST_RUN Execute all test script files of a folder and all its
output_tests_from_mfile Build a test_suite with all test* methods from a .m-file.
SOURCE CODE
%Console progress listener implementation.
%  Displays test results live on the console as they are being executed.
%
%  See init_results, next_result
%  This Software and all associated files are released unter the
%  GNU General Public License (GPL), see LICENSE for details.
%
%  $Id$
function self = mlunit_progress_listener_console()
error(nargchk(0, 0, nargin, 'struct'));
self = struct();
self = class(self, 'mlunit_progress_listener_console', mlunit_progress_listener);