Description of run
mlUnit > src > @test_case > run.m
run
PURPOSE
test_case/run executes the test case and saves the results in result.
SYNOPSIS
function [self, result] = run(self, result)
DESCRIPTION
test_case/run executes the test case and saves the results in result.
  Example
  =======
  There are two ways of calling run:
  1) [test, result] = run(test) uses the default test result.
  2) [test, result] = run(test, result) uses the result given as
     paramater, which allows to collect the result of a number of tests
     within one test result.
  See also TEST_CASE.
CROSS-REFERENCE INFORMATION
This function calls:
set_up function_test_case/set_up calls the set_up_function by the function handle to set up the fixture and is called everytime before a test is executed.
tear_down test_case/tear_down called calls the tear_down_function by the function handle everytime after a test is executed for cleaning up the fixture.
add_failure gui_test_result/add_failure calls the inherited method from test_result and the update method, which updates the different gui objects.
add_success gui_test_result/add_success calls the inherited method from test_result and the update method, which updates the different gui objects.
start_test gui_test_result/start_test calls the inherited method from test_result.
default_test_result test_case/default_test_result returns s default test_result object.
set_up test_case/set_up sets up the fixture and is called everytime before a test is executed.
tear_down test_case/tear_down called everytime after a test is executed for cleaning up the fixture.
add_error_with_stack test_result/add_error_with_stack adds an error for the test to the list of errors using the struct members of lasterror (file and stack) to generate a more detailed error report.
add_failure test_result/add_failure adds a failure for the test to the list of failures.
add_success test_result/add_success is an empty method for classes, which might do some action on a successful test.
start_test test_result/start_test indicates that a test will be started.
stop_test test_result/stop_test indicates that a test has been finished.
add_failure text_test_result/add_failure calls the inherited method from test_result and writes out an 'F' (verbosity == 1) or 'FAILURE' (verbosity == 2) to the stream.
add_success text_test_result/add_success calls the inherited method from test_result and writes out an '.' (verbosity == 1) or 'OK' (verbosity == 2) to the stream.
start_test text_test_result/start_test calls the inherited method from test_result and writes out the name of the test (both only at verbosity == 2) to the stream.
This function is called by:
gui gui_test_runner/gui execute the graphical user interface of mlUnit.
load gui_test_runner/loads starts the graphical user interface of mlUnit with saved parameters from the .mat-file mlunit.tmp.
run mlunit/run executes the the graphical user interface of mlUnit.
run test_suite/run executes the test suite and saves the results in result.
run text_test_runner/run execute the test and writes the results to a stream in textual form (using TextTestResult).
SOURCE CODE
function [self, result] = run(self, result)
%test_case/run executes the test case and saves the results in result.
%
%  Example
%  =======
%  There are two ways of calling run:
%
%  1) [test, result] = run(test) uses the default test result.
%
%  2) [test, result] = run(test, result) uses the result given as
%     paramater, which allows to collect the result of a number of tests
%     within one test result.
%
%  See also TEST_CASE.
%  This Software and all associated files are released unter the
%  GNU General Public License (GPL), see LICENSE for details.
%
%  §Author: Thomas Dohmke <thomas@dohmke.de> §
%  $Id: run.m 249 2007-01-26 22:59:59Z thomi $
if (nargin == 1)
    result = default_test_result(self);
end;
result = start_test(result, self);
try
    try
        self = set_up(self);
    catch
        result = add_error_with_stack(result, self, lasterror);
        return;
    end;
    ok = 0;
    try
        method = self.name;
        self = eval([method, '(self)']);
        ok = 1;
    catch
        err = lasterror;
        errmsg = err.message;
        failure = strfind(errmsg, 'MLUNIT FAILURE');
        if (size(failure) > 0)
            result = add_failure(result, ...
                self, ...
                errmsg(failure(1) + 15:length(errmsg)));
        else
            if (~isfield(err, 'stack'))
                err.stack(1).file = char(which(self.name));
                err.stack(1).line = '1';
                err.stack = vertcat(err.stack, dbstack('-completenames'));
            end;
            result = add_error_with_stack(result, self, err);
        end;
    end;
    try
        self = tear_down(self);
    catch
        result = add_error_with_stack(result, self, lasterror);
        ok = 0;
    end;
    if (ok)
        result = add_success(result, self);
    end;
catch
end;
result = stop_test(result, self);