Description of recursive_test_run
Home > mlunit > automation > recursive_test_run.m
recursive_test_run
PURPOSE
RECURSIVE_TEST_RUN Execute all test script files of a folder and all its
SYNOPSIS
function recursive_test_run(testobj, targetdir)
DESCRIPTION
RECURSIVE_TEST_RUN Execute all test script files of a folder and all its
subfolders recursively.
  RECURSIVE_TEST_RUN(BASEDIR) executes all test scripts found in BASEDIR
  and its sub directories. Reports and log files will go into BASEDIR.
  BASEDIR may be a relative or an absolute path.
  RECURSIVE_TEST_RUN(SUITE) executes just one test suite SUITE.
  RECURSIVE_TEST_RUN(TESTOBJ, TARGETDIR) does the same, but lets reports
  and logs be created in the TARGETDIR directory.
  See also mlunit_gui, mlunit_suite_runner
CROSS-REFERENCE INFORMATION
This function calls:
mlunit_progress_listener_console Console progress listener implementation.
add_listener Add a progress listener object to the list of subscribers.
mlunit_suite_runner Execute a single test suite
run_suite_collection Execute one or several test suites.
This function is called by:
SOURCE CODE
function recursive_test_run(testobj, targetdir)
%RECURSIVE_TEST_RUN Execute all test script files of a folder and all its
%subfolders recursively.
%  RECURSIVE_TEST_RUN(BASEDIR) executes all test scripts found in BASEDIR
%  and its sub directories. Reports and log files will go into BASEDIR.
%  BASEDIR may be a relative or an absolute path.
%
%  RECURSIVE_TEST_RUN(SUITE) executes just one test suite SUITE.
%
%  RECURSIVE_TEST_RUN(TESTOBJ, TARGETDIR) does the same, but lets reports
%  and logs be created in the TARGETDIR directory.
%
%  See also mlunit_gui, mlunit_suite_runner
%  This Software and all associated files are released unter the
%  GNU General Public License (GPL), see LICENSE for details.
%
%  $Id$
if nargin < 1, testobj = pwd; end
suite_runner = add_listener(mlunit_suite_runner, mlunit_progress_listener_console);
if nargin < 2
    run_suite_collection(suite_runner, testobj);
else
    run_suite_collection(suite_runner, testobj, targetdir);
end