Description of add_listener
Home > mlunit > @mlunit_suite_runner > add_listener.m
add_listener
PURPOSE
Add a progress listener object to the list of subscribers.
SYNOPSIS
function self = add_listener(self, listener)
DESCRIPTION
Add a progress listener object to the list of subscribers.
  Example:
  >> sr = add_listener(mlunit_suite_runner, mlunit_progress_listener);
  % This sets up an abstract base listener, which will throw errors
  % when being executed.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
gui mlunit_gui/gui execute the graphical user interface of mlUnit.
load_tests_from_mfile test_loader/load_tests_from_mfile returns a test_suite with all
recursive_test_run RECURSIVE_TEST_RUN Execute all test script files of a folder and all its
output_tests_from_mfile Build a test_suite with all test* methods from a .m-file.
SOURCE CODE
%Add a progress listener object to the list of subscribers.
%
%  Example:
%
%  >> sr = add_listener(mlunit_suite_runner, mlunit_progress_listener);
%  % This sets up an abstract base listener, which will throw errors
%  % when being executed.
%  This Software and all associated files are released unter the
%  GNU General Public License (GPL), see LICENSE for details.
%
%  $Id$
function self = add_listener(self, listener)
error(nargchk(2,2,nargin,'struct'));
if ~isa(listener, 'mlunit_progress_listener'), error('listener need be mlunit_progress_listener'); end
% Maintain list of listeners as cell array, because R2007b would spit
% segmentation violations when using native array.
self.listeners{end+1} = listener;