Description of get_object
Home > src > @gui_test_runner > get_object.m
get_object
PURPOSE
gui_test_runner/get_object returns the singleton object of the gui window.
SYNOPSIS
function self = get_object(self) %#ok
DESCRIPTION
gui_test_runner/get_object returns the singleton object of the gui window.
  Example
  =======
         run(gui_test_runner, 'mlunit_all_tests');
         runner = get_object(gui_test_runner)
  See also GUI_TEST_RUNNER.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
close gui_test_runner/close closes the graphical user interface of mlUnit.
gui gui_test_runner/gui execute the graphical user interface of mlUnit.
load gui_test_runner/loads starts the graphical user interface of mlUnit with
run gui_test_runner/run is an alternative method to execute the graphical
save gui_test_runner/save saves the parameters of the graphical user interface
SOURCE CODE
function self = get_object(self) %#ok
%gui_test_runner/get_object returns the singleton object of the gui window.
%
%  Example
%  =======
%         run(gui_test_runner, 'mlunit_all_tests');
%         runner = get_object(gui_test_runner)
%
%  See also GUI_TEST_RUNNER.
%  This Software and all associated files are released unter the
%  GNU General Public License (GPL), see LICENSE for details.
%
%  §Author: Thomas Dohmke <thomas@dohmke.de> §
%  $Id: get_object.m 158 2007-01-03 20:25:39Z thomi $
shh = get(0, 'ShowHiddenHandles');
set(0, 'ShowHiddenHandles', 'on');
handle = findall(0, 'Name', 'mlUnit');
self = get(handle, 'UserData');
set(0, 'ShowHiddenHandles', shh);