Description of mlunit_suite_runner
Home > src > @mlunit_suite_runner > mlunit_suite_runner.m
mlunit_suite_runner
PURPOSE
Execute a single test suite
SYNOPSIS
function self = mlunit_suite_runner()
DESCRIPTION
Execute a single test suite
  Implemented as class in order to manage progress listener subscriptions.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
gui mlunit_gui/gui execute the graphical user interface of mlUnit.
load_tests_from_mfile test_loader/load_tests_from_mfile returns a test_suite with all
recursive_test_run RECURSIVE_TEST_RUN Execute all test script files of a folder and all its
SOURCE CODE
%Execute a single test suite
%  Implemented as class in order to manage progress listener subscriptions.
%  This Software and all associated files are released unter the
%  GNU General Public License (GPL), see LICENSE for details.
%
%  $Id$
function self = mlunit_suite_runner()
% default value, maintain listeners in cell array, see add_listener
self.listeners = {};
% create instance
self = class(self, 'mlunit_suite_runner');