Description of tests
Home > src > @test_suite > tests.m
tests
PURPOSE
SYNOPSIS
function t = tests(self)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
add_tests test_suite/add_test adds a cell array of tests to the test suite.
count_test_cases test_suite/count_test_cases returns the number of test cases executed
test_suite test_suite contructor.
SOURCE CODE
function t = tests(self)
t = self.tests;