Description of str
Home > src > @test_case > str.m
str
PURPOSE
test_case/str returns a string with the method and class name of the test.
SYNOPSIS
function s = str(self)
DESCRIPTION
test_case/str returns a string with the method and class name of the test.
  Example
  =======
  If a test method is defined as follows
           function test_method
               assert_true(0 == sin(0));
           end
  belonging to a class my_test, which is instantiated for example
           test = my_test('test_method');
  str will return:
           my_test('test_method')
  See also TEST_CASE.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
gui mlunit_gui/gui execute the graphical user interface of mlUnit.
shorten_error_text mlunit_gui/set_shorten shortens the directory paths of
load_tests_from_mfile test_loader/load_tests_from_mfile returns a test_suite with all
SOURCE CODE
function s = str(self)
%test_case/str returns a string with the method and class name of the test.
%
%  Example
%  =======
%  If a test method is defined as follows
%           function test_method
%               assert_true(0 == sin(0));
%           end
%  belonging to a class my_test, which is instantiated for example
%           test = my_test('test_method');
%  str will return:
%           my_test('test_method')
%
%  See also TEST_CASE.
%  This Software and all associated files are released unter the
%  GNU General Public License (GPL), see LICENSE for details.
%
%  §Author: Thomas Dohmke <thomas@dohmke.de> §
%  $Id: str.m 61 2006-09-21 19:11:35Z thomi $
s = [class(self), '(''', self.name, ''')'];