Description of update
mlUnit > src > @gui_test_result > update.m
update
PURPOSE
gui_test_result/update update the different gui object: the progress bar, the text area with the number of test ran etc., and the listbox with all errors and failures.
SYNOPSIS
function self = update(self)
DESCRIPTION
gui_test_result/update update the different gui object: the progress bar,
the text area with the number of test ran etc., and the listbox with all
errors and failures.
  Example
  =======
  update is called after the adding of each error, failure or success in
  add_error, etc:
         self = update(self);
  See also GUI_TEST_RESULT/ADD_ERROR, GUI_TEST_RESULT/ADD_FAILURE,
           GUI_TEST_RESULT/ADD_SUCCESS.
CROSS-REFERENCE INFORMATION
This function calls:
print_errors gui_test_result/print_errors creates the list and description of all errors and failures and set them to the listbox of errors and failures.
progress_bar gui_test_result/progres_bar updates the progress bar of the mlUnit gui.
texts gui_test_result/texts creates the text area with the number of tests ran, the number of errors and the number of failures.
print_errors text_test_result/print_errors writes the description of all errors and failures to the stream.
This function is called by:
add_error gui_test_result/add_error calls the inherited method from test_result and the update method, which updates the different gui objects.
add_failure gui_test_result/add_failure calls the inherited method from test_result and the update method, which updates the different gui objects.
add_success gui_test_result/add_success calls the inherited method from test_result and the update method, which updates the different gui objects.
gui gui_test_runner/gui execute the graphical user interface of mlUnit.
SOURCE CODE
function self = update(self)
%gui_test_result/update update the different gui object: the progress bar,
%the text area with the number of test ran etc., and the listbox with all
%errors and failures.
%
%  Example
%  =======
%  update is called after the adding of each error, failure or success in
%  add_error, etc:
%         self = update(self);
%
%  See also GUI_TEST_RESULT/ADD_ERROR, GUI_TEST_RESULT/ADD_FAILURE,
%           GUI_TEST_RESULT/ADD_SUCCESS.
%  This Software and all associated files are released unter the
%  GNU General Public License (GPL), see LICENSE for details.
%
%  §Author: Thomas Dohmke <thomas@dohmke.de> §
%  $Id: update.m 28 2006-06-11 15:11:59Z thomi $
progress_bar(self);
texts(self);
print_errors(self);
drawnow;