Description of get_tests_run
mlUnit > src > @test_result > get_tests_run.m
get_tests_run
PURPOSE
test_result/tests_run returns the number of tests executed.
SYNOPSIS
function tests_run = get_tests_run(self)
DESCRIPTION
test_result/tests_run returns the number of tests executed.
  Example
  =======
  get_tests_run is called for example from text_test_runner/run:
         tests_run = get_tests_run(result);
  See also TEXT_TEST_RUNNER/RUN.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
progress_bar gui_test_result/progres_bar updates the progress bar of the mlUnit gui.
texts gui_test_result/texts creates the text area with the number of tests ran, the number of errors and the number of failures.
run text_test_runner/run execute the test and writes the results to a stream in textual form (using TextTestResult).
SOURCE CODE
function tests_run = get_tests_run(self)
%test_result/tests_run returns the number of tests executed.
%
%  Example
%  =======
%  get_tests_run is called for example from text_test_runner/run:
%         tests_run = get_tests_run(result);
%
%  See also TEXT_TEST_RUNNER/RUN.
%  This Software and all associated files are released unter the
%  GNU General Public License (GPL), see LICENSE for details.
%
%  §Author: Thomas Dohmke <thomas@dohmke.de> §
%  $Id: get_tests_run.m 30 2006-06-11 15:53:00Z thomi $
tests_run = self.tests_run;