Description of display_meta_error
Home > mlunit > @mlunit_progress_listener_gui > display_meta_error.m
display_meta_error
PURPOSE
Display an error that occurred outside of any test execution.
SYNOPSIS
function self = display_meta_error(self, meta_error)
DESCRIPTION
Display an error that occurred outside of any test execution.
  We want to put any meta errors up on display in the GUI directly, as users
  might miss console error dumps when working with the GUI.
  SELF = display_meta_error(SELF, META) puts an error up for display, but does
  not alter any test/error/failure count. META is an mlunit_errorinfo instance.
CROSS-REFERENCE INFORMATION
This function calls:
get_message_with_stack Get an error's message and stack as single string.
mlunit_errorinfo Information about one error. Formattable.
add_to_errorlist Add an entry to the GUI's error list.
update_display Update all listener elements of the GUI.
This function is called by:
gui mlunit_gui/gui execute the graphical user interface of mlUnit.
SUBFUNCTIONS
function result = loc_iserror(type)
SOURCE CODE
%Display an error that occurred outside of any test execution.
%  We want to put any meta errors up on display in the GUI directly, as users
%  might miss console error dumps when working with the GUI.
%
%  SELF = display_meta_error(SELF, META) puts an error up for display, but does
%  not alter any test/error/failure count. META is an mlunit_errorinfo instance.
%  This Software and all associated files are released unter the
%  GNU General Public License (GPL), see LICENSE for details.
%
%  $Id$
function self = display_meta_error(self, meta_error)
error(nargchk(2, 2, nargin, 'struct'));
if ~loc_iserror(meta_error), error('meta_error argument need be error struct'); end
% don't reset any current gui state; it might be helpful to know how many
% testcases executed before breakdown
errmsg = get_message_with_stack(mlunit_errorinfo(meta_error));
add_to_errorlist(self, 'ERROR', 'mlunit_gui', errmsg);
update_display(self);
function result = loc_iserror(type)
    result = isstruct(type) && ...
        numel(type) == 1 && ...
        all(isfield(type, {'identifier', 'message', 'stack'}));