Description of assert_error
Home > src > assertions > assert_error.m
assert_error
PURPOSE
ASSERT_ERROR Raise an error if a call does not throw an error.
SYNOPSIS
function assert_error(func, errspec, varargin)
DESCRIPTION
ASSERT_ERROR Raise an error if a call does not throw an error.
  ASSERT_ERROR(FUNC) calls the function handle FUNC and raises an error if the
  function returns without error. Use it to assert that a certain function
  definitely raises an error. If you need to bind variable values to the
  function's input arguments, do so by an intermediate anonymous function.
  Also see examples.
  ASSERT_ERROR(FUNC, ERRID) does the same. Also raises an error when the
  identifier of FUNC's error does not equal string ERRID.
  ASSERT_ERROR(FUNC, ERRID, MSG) does the same. Adds a custom message to the
  front of the failure message. The MSG argument may also be used with the
  following signatures.
  ASSERT_ERROR(FUNC, ERRSTRUCT) does the same, but with a typical error
  structure as argument. Set any of fields 'identifier', 'message', 'stack' in
  ERRSTRUCT to let each be compared to the actual error's fields. Only set
  fields will be compared. This enables you to compare the call stack. You
  can limit the comparison to some parts of a call stack's fields. The fields
  are: file, name, line. By providing only one or two of them in your expected
  call stack structure, only those fields will be compared.
  An empty struct() ERRSTRUCT checks for any error at all.
  ASSERT_ERROR(EXPRSTRING, ERRID/ERRSTRUCT) evaluates the string EXPRSTRING
  and raises an error if the evaluation did not raise an error itself. Use this
  to rather call arbitrary MATLAB expressions instead of single functions. Same
  rules for ERRID/ERRSTRUCT arguments as above apply.
  Examples
     % assert some error being issued, here from missing input arguments
     assert_error('error');
     % assert some specific error by specifying its message
     assert_error('error(''huh\nha'');', 'huh\nha');
     % use an anonymous function for injecting variable values
     v1 = 3; v2 = {};
     assert_error(@() max(v1, v2), 'MATLAB:UndefinedFunction');
  See also  MLUNIT_FAIL, ASSERT_TRUE, ASSERT_WARNING
CROSS-REFERENCE INFORMATION
This function calls:
mlunit_fail_with_reason MLUNIT_FAIL_WITH_REASON Raise an error with a specific reason message.
printable PRINTABLE Convert any type into a string suitable for embedding into messages.
mlunit_strjoin MLUNIT_STRJOIN Concatenate a string cell's items, using a separator.
This function is called by:
SUBFUNCTIONS
function diff = error_struct_diff(expected, actual)
function string = diff2string(diff)
SOURCE CODE
function assert_error(func, errspec, varargin)
%ASSERT_ERROR Raise an error if a call does not throw an error.
%  ASSERT_ERROR(FUNC) calls the function handle FUNC and raises an error if the
%  function returns without error. Use it to assert that a certain function
%  definitely raises an error. If you need to bind variable values to the
%  function's input arguments, do so by an intermediate anonymous function.
%  Also see examples.
%
%  ASSERT_ERROR(FUNC, ERRID) does the same. Also raises an error when the
%  identifier of FUNC's error does not equal string ERRID.
%
%  ASSERT_ERROR(FUNC, ERRID, MSG) does the same. Adds a custom message to the
%  front of the failure message. The MSG argument may also be used with the
%  following signatures.
%
%  ASSERT_ERROR(FUNC, ERRSTRUCT) does the same, but with a typical error
%  structure as argument. Set any of fields 'identifier', 'message', 'stack' in
%  ERRSTRUCT to let each be compared to the actual error's fields. Only set
%  fields will be compared. This enables you to compare the call stack. You
%  can limit the comparison to some parts of a call stack's fields. The fields
%  are: file, name, line. By providing only one or two of them in your expected
%  call stack structure, only those fields will be compared.
%  An empty struct() ERRSTRUCT checks for any error at all.
%
%  ASSERT_ERROR(EXPRSTRING, ERRID/ERRSTRUCT) evaluates the string EXPRSTRING
%  and raises an error if the evaluation did not raise an error itself. Use this
%  to rather call arbitrary MATLAB expressions instead of single functions. Same
%  rules for ERRID/ERRSTRUCT arguments as above apply.
%
%  Examples
%     % assert some error being issued, here from missing input arguments
%     assert_error('error');
%
%     % assert some specific error by specifying its message
%     assert_error('error(''huh\nha'');', 'huh\nha');
%
%     % use an anonymous function for injecting variable values
%     v1 = 3; v2 = {};
%     assert_error(@() max(v1, v2), 'MATLAB:UndefinedFunction');
%
%  See also  MLUNIT_FAIL, ASSERT_TRUE, ASSERT_WARNING
%  This Software and all associated files are released unter the
%  GNU General Public License (GPL), see LICENSE for details.
%
%  $Id$
error(nargchk(1, Inf, nargin, 'struct'));
% determine what to check for
if nargin < 2
   % checks for any error at all
   errcomp = struct();
elseif ischar(errspec)
   % checks for identifier
   errcomp = struct('identifier', {errspec});
elseif isstruct(errspec)
   % checks for anything the user specified
   errcomp = errspec;
else
   error('assert_error: ERRSPEC argument must be either an error id string or a error struct.');
end
% execute function/evalstring
bCaught = false;
try
   if isa(func, 'function_handle')
      func();
   else
      evalin('caller', func);
   end
catch
   bCaught = true;
   % use lasterror instead of catch for R2006b compatibility
   differences = error_struct_diff(errcomp, lasterror());
   % we have a match when there are no relevant differences
   bErrorMatch = isempty(fieldnames(differences));
end
% evaluate findings
if ~bCaught
   % no error at all is a failed expectation
   mlunit_fail_with_reason('Error expected, but none occurred.', varargin{:});
elseif ~bErrorMatch
   error_msg = sprintf('Error occurred, but did not match criteria. %s', diff2string(differences));
   mlunit_fail_with_reason(error_msg, varargin{:});
end
% Return a structure with only those fields that do not equal throughout error
% structures expected and actual. Only compares fields that both structures
% have. Each of the returned structure's field's values themselves is a structure
% with fields 'expected' and 'actual'.
function diff = error_struct_diff(expected, actual)
   diff = struct();
   % compare those error details
   fields = intersect(fieldnames(expected), fieldnames(actual));
   % compare each and every field for equality
   for f = 1:length(fields)
      % actual error message needs to be cleaned from assert_error specific stuff
      if strcmp(fields{f}, 'message')
         % Eat first line that should read 'Error using ==> assert_error', terminated
         % by a newline. The actual message comes after it. Filter the offending line
         % with a regular expression rather than a simple strrep, because after '==>',
         % MATLAB puts an HTML statement from R2007b on, and plain text before.
         actual.message = regexprep(actual.message, 'Error using .*\n', '', 'dotexceptnewline');
      end
      % filter actual stack fields to include only expected outputs
      if strcmp(fields{f}, 'stack')
         surplus_fields_actual = setdiff(fieldnames(actual.stack), fieldnames(expected.stack));
         surplus_fields_expected = setdiff(fieldnames(expected.stack), fieldnames(actual.stack));
         actual.stack = rmfield(actual.stack, surplus_fields_actual);
         expected.stack = rmfield(expected.stack, surplus_fields_expected);
      end
      if ~isequal(expected.(fields{f}), actual.(fields{f}))
         diff.(fields{f}) = struct('expected', {expected.(fields{f})}, 'actual', {actual.(fields{f})});
      end
   end
function string = diff2string(diff)
   diffstring = @(field) ['Expected error ' field ' ' printable(diff.(field).expected) ' actually was ' printable(diff.(field).actual) '.'];
   diffstrings = cellfun(diffstring, fieldnames(diff), 'UniformOutput', false);
   string = mlunit_strjoin(diffstrings, sprintf('\n'));