Description of texts
mlUnit > src > @gui_test_result > texts.m
texts
PURPOSE
gui_test_result/texts creates the text area with the number of tests ran, the number of errors and the number of failures.
SYNOPSIS
function texts(self)
DESCRIPTION
gui_test_result/texts creates the text area with the number of tests ran, the
number of errors and the number of failures.
  Example
  =======
  texts is called for example from gui_test_result/update:
         texts(self);
  See also GUI_TEST_RESULT/UPDATE.
CROSS-REFERENCE INFORMATION
This function calls:
get_errors test_result/get_errors returns the number of errors.
get_failures test_result/get_errors returns the number of failures.
get_tests_run test_result/tests_run returns the number of tests executed.
This function is called by:
update gui_test_result/update update the different gui object: the progress bar, the text area with the number of test ran etc., and the listbox with all errors and failures.
SOURCE CODE
function texts(self)
%gui_test_result/texts creates the text area with the number of tests ran, the
%number of errors and the number of failures.
%
%  Example
%  =======
%  texts is called for example from gui_test_result/update:
%         texts(self);
%
%  See also GUI_TEST_RESULT/UPDATE.
%  This Software and all associated files are released unter the
%  GNU General Public License (GPL), see LICENSE for details.
%
%  §Author: Thomas Dohmke <thomas@dohmke.de> §
%  $Id: texts.m 28 2006-06-11 15:11:59Z thomi $
set(self.text_runs, 'String', ['Runs: ', num2str(get_tests_run(self)), ...
    ' / Errors: ', num2str(get_errors(self)), ...
    ' / Failures: ', num2str(get_failures(self))]);