Description of shorten_error_text
Home > src > @mlunit_gui > shorten_error_text.m
shorten_error_text
PURPOSE
mlunit_gui/set_shorten shortens the directory paths of
SYNOPSIS
function shortened_text = shorten_error_text(self, error_text)
DESCRIPTION
mlunit_gui/set_shorten shortens the directory paths of
an error message. This is helpful for a small width of the gui window.
  Example
  =======
  The method is internal to the mlUnit framework and should not be called
  directly.
  See also mlunit_gui, mlunit_gui/GUI,
           mlunit_gui/SET_SHORTEN.
CROSS-REFERENCE INFORMATION
This function calls:
str function_test_case/str return a string with the method and class name of
get_line_expression mlunit_gui/get_line_expression returns the regular expression a line
str mlunit_gui/str return a string with the class name.
str test_case/str returns a string with the method and class name of the test.
This function is called by:
gui mlunit_gui/gui execute the graphical user interface of mlUnit.
SOURCE CODE
function shortened_text = shorten_error_text(self, error_text)
%mlunit_gui/set_shorten shortens the directory paths of
%an error message. This is helpful for a small width of the gui window.
%
%  Example
%  =======
%  The method is internal to the mlUnit framework and should not be called
%  directly.
%
%  See also mlunit_gui, mlunit_gui/GUI,
%           mlunit_gui/SET_SHORTEN.
%  This Software and all associated files are released unter the
%  GNU General Public License (GPL), see LICENSE for details.
%
%  §Author: Thomas Dohmke <thomas@dohmke.de> §
%  $Id: shorten_error_text.m 252 2007-01-27 21:02:36Z thomi $
if (self.shorten == 0)
    shortened_text = error_text;
    return;
end;
error_lines = strread(error_text, '%s', 'delimiter', '\n'); %regexp(error_text, '(.*)', 'tokens', 'dotexceptnewline');
if (isempty(error_lines))
    shortened_text = error_text;
    return;
end;
shortened_text = '';
for i = 1:length(error_lines)
    line = error_lines{i};
    [tokens] = regexp(char(line), ['^', get_line_expression(self)], 'tokens', 'once');
    if (length(tokens) == 2)
        token = tokens{1};
        token = strrep(token, '\', '/');
        str = cell(1);
        [str{1}, rem] = strtok(token, '\/'); %#ok
        j = 2;
        while (length(rem) > 0)
            [str{j}, rem] = strtok(rem, '\/'); %#ok
            j = j + 1;
        end;
        if (length(str) > 1)
            if (strcmp(token(1), '/'))
                line = ['/', str{1}, '/../', str{end - 1}, '/', str{end}];
            else
                line = [str{1}, '/../', str{end - 1}, '/', str{end}];
            end;
        else
            line = str(1);
        end;
        line = sprintf('  In %s at line %s', char(line), tokens{2});
    end;
    if (isempty(shortened_text))
        shortened_text = char(line);
    else
        shortened_text = sprintf('%s\n%s', char(shortened_text), char(line));
    end;
end;