Description of get_message_with_stack
Home > src > @mlunit_errorinfo > get_message_with_stack.m
get_message_with_stack
PURPOSE
Get an error's message and stack as single string.
SYNOPSIS
function message = get_message_with_stack(self)
DESCRIPTION
Get an error's message and stack as single string.
  get_message_with_stack works on the internally buffered error information
  that you provided in mlunit_errorinfo's constructor. The actual message and
  stack get processed according to it being an mlUnit failure or a plain error.
  message = get_message_with_stack(self) returns a char array containing the
  message and stack.
  The stack format can be changed by the mlUnit parameter 'linked_trace'.
CROSS-REFERENCE INFORMATION
This function calls:
filter_failure_stack Restrict a failure's stack to items relevant to the user.
filter_lasterror_wraps Free error message of leading 'Error:' or 'Error using' lines.
is_failure Return whether this error represents a failure rather than a common error.
mlunit_param MLUNIT_PARAM Set or get an mlunit parameter
This function is called by:
next_result Update display with next test case result.
display_meta_error Display an error that occurred outside of any test execution.
next_result Update display with next test case result.
run_suite_collection Execute one or several test suites.
run_test Execute a single test case.
SUBFUNCTIONS
function stackstring = loc_print_stack(stack)
function stackline = loc_print_stackline(stackitem)
SOURCE CODE
%Get an error's message and stack as single string.
%  get_message_with_stack works on the internally buffered error information
%  that you provided in mlunit_errorinfo's constructor. The actual message and
%  stack get processed according to it being an mlUnit failure or a plain error.
%
%  message = get_message_with_stack(self) returns a char array containing the
%  message and stack.
%
%  The stack format can be changed by the mlUnit parameter 'linked_trace'.
%  This Software and all associated files are released unter the
%  GNU General Public License (GPL), see LICENSE for details.
%
%  $Id$
function message = get_message_with_stack(self)
% obtain message and stack
[message, stack] = filter_lasterror_wraps(self);
% reduce the stack of failures for better overview
if is_failure(self)
    stack = filter_failure_stack(self, stack);
end
% put message and stack together
message = [message, loc_print_stack(stack)];
%Build a single stactracke string out of a stack structure.
%If there are stack items at all, start with a leading newline.
%  stack is the stack structure as returned by lasterror().stack or dbstack().
function stackstring = loc_print_stack(stack)
stackstring = '';
for i = 1:size(stack, 1)
    stackstring = sprintf('%s\n%s', ...
        stackstring, ...
        loc_print_stackline(stack(i)));
end
% Build a single stacktrace line for a single stacktrace item.
%   stackitem has fields as returned by lasterror().stack or dbstack().
function stackline = loc_print_stackline(stackitem)
display_name = stackitem.file;
if mlunit_param('abbrev_trace')
    [dummy, filename, ext] = fileparts(stackitem.file);
    display_name = [filename ext];
end
if mlunit_param('linked_trace')
    hrefvalue = sprintf('matlab:opentoline(''%s'',%d)', ...
        stackitem.file, stackitem.line);
    stackline = sprintf('In <a href="%s">%s</a> at line %d', ...
        hrefvalue, display_name, stackitem.line);
else
    stackline = sprintf('In %s at line %d', ...
        display_name, stackitem.line);
end